<!-- Navigation bar, which will appear on every page -->
<header class="header">
  <!-- Navigation bar -->
  <nav class="navbar">
    <!--  Logo and website name -->
    <a href="index.php" class="nav-logo"><h1><i class="material-icons md-36">menu_book</i>Bookshopper</h1></a>
    <!-- Navigation links -->
    <ul class="nav-menu">
      <li class="nav-item">
        <a href="search.php" class="nav-link">Search</a>
      </li>
      <li class="nav-item">
        <a href="submission.php" class="nav-link">Submit a Location</a>
      </li>
      <li class="nav-item">
        <a id="loginnav" href="login.php" class="nav-link">Log In</a>
      </li>
      <li class="nav-item">
        <a id="signupnav" href="registration.php" class="nav-link">Sign Up</a>
      </li>
    </ul>
    <!-- Hamburger menu, not displayed unless screen is small enough -->
    <div class="hamburger">
      <span class="bar"></span>
      <span class="bar"></span>
      <span class="bar"></span>
    </div>    
  </nav>   
</header>